Bump tokio and reqwest versions
New Tokio is incompatible with libraries assuming old Tokio:

```
thread 'main' panicked at 'not currently running on a Tokio 0.2.x runtime.', external/raze__tokio__0_2_25/src/runtime/handle.rs:118:28
```